[tool.poetry]
name = "responsive-image-utilities"
version = "0.1.0"
description = ""
authors = ["C. Thomas Brittain <cthomasbrittain@hotmail.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.8.0"
pillow = "^10.4.0"
sewar = "^0.4.6"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.8.0"
ruff = "^0.6.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html
# https://pytest-with-eric.com/configuration/pytest-config-file/#Using-pytest-ini
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "integration",
]
